import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root=new URL('../',import.meta.url);
const source=await readFile(new URL('design-system/tokens.css',root),'utf8');
assert.equal(createHash('sha256').update(source).digest('hex'),'71f2d7f71226a9fe3f9066d26cfd43a65cc642ac96ce1fe5bce7081c8d7b1f82','Portfolio source tokens differ from the verified release');
const generated=await readFile(new URL('assets/design-system/portfolio-tokens.css',root),'utf8');
assert.equal(generated,'/* Generated by scripts/sync-portfolio-theme.mjs; source design-system/tokens.css. */\n'+source.replace(/--[a-z][a-z0-9-]*/g,name=>'--portfolio-'+name.slice(2)),'Generated namespace changed a source value');
const data=JSON.parse(await readFile(new URL('data/credentials.json',root),'utf8'));
for(const file of ['index.html',...data.credentials.map(c=>c.detailPath)]){
 const html=await readFile(new URL(file.endsWith('/')?file+'index.html':file,root),'utf8');
 const prefix=file==='index.html'?'':'../../';
 assert.ok(html.includes(`href="${prefix}styles.css"`));
 assert.ok(html.includes(`href="${prefix}assets/design-system/portfolio-tokens.css"`),file);
 assert.ok(html.includes(`href="${prefix}portfolio-theme.css"`),file);
 assert.ok(html.indexOf(`href="${prefix}styles.css"`)<html.indexOf(`href="${prefix}portfolio-theme.css"`),'Skin must load after original reel styles');
}
console.log('PASS: verified upstream token hash, namespace preserves every source value, and standalone theme loading on all 18 pages.');
